Feature/8/NewCard
dahun-lee-daji/todo-list pull request #19
Opened 2021-04-12 07:43 UTC by jhpark-ZG

### 작업 내용

- [x]  카드 추가 화면 : modal
- [x]  "X" button : dismiss
- [x]  PlaceHolder 지정
- [x]  본문이 길어지면 3줄까지 multiLine, 줄이 늘어나면 Card self-Resizing
- [ ]  글자 수 증가에 따라 box가 아래로 늘어나야 함
- [ ]  등록 버튼 시 server로 newCardData POST
- [ ]  Title, Content 가 비어있을 떄 : "등록"button.isEnable = false

### 고민과 해결

cellData가 의 내부 속성을 tableViewDataSource에서 직접 참조하였습니다.
모델에서 post 할 방법을 떠올리긴 했지만, 일단 cellData가 private이 아닌 이유가 있을 것이라 생각하여 그대로 진행하였습니다.
혹시 이 부분에서 다른 방법이 생각 나시면 피드백 부탁드려요~ (저도 고민해보겠습니다~)

2021-04-12 18:13 UTC, dahun-lee-daji requested changes

2021-04-12 18:13 UTC, dahun-lee-daji commented on frontend/ToDoListApp/ToDoListApp/ColumnSection/Controllers/ModalViewController.swift
> +        self.titleTextField.delegate = titleTextFieldDelegate
위에 initializer 중 init(nib~) 에는 delegate지정하는 내용이 있는데, init(coder:~)에는 없네요,
그래서 viewDidLoad에 다시 지정해주시는 건가요?

2021-04-12 18:13 UTC, dahun-lee-daji commented on frontend/ToDoListApp/ToDoListApp/ColumnSection/Controllers/ModalViewController.swift
> +        let cellData : CellData = CellData.init(cardId: 0, title: titlefieldText, content: contentFieldText, isApp: false, createdTime: "", position: 0)
새로운 CellData의 Id가 0으로 반복해서 들어가게 구현된 것 같네요, 추후 수정될 내용일까요?

2021-04-13 01:15 UTC, jhpark-ZG commented on frontend/ToDoListApp/ToDoListApp/ColumnSection/Controllers/ModalViewController.swift
> +        let cellData : CellData = CellData.init(cardId: 0, title: titlefieldText, content: contentFieldText, isApp: false, createdTime: "", position: 0)
네 일단 임시로 넣었습니다.

2021-04-13 01:33 UTC, jhpark-ZG commented on frontend/ToDoListApp/ToDoListApp/ColumnSection/Controllers/ModalViewController.swift
> +        self.titleTextField.delegate = titleTextFieldDelegate
네 init(coder:) 에서 지정하면 앱이 종료되어 버렸습니다.

2021-04-13 01:33 UTC, dahun-lee-daji commented
차후에 수정하신다 하셔서 머지 진행하도록 하겠습니다!

2021-04-13 01:33 UTC, merged